/* SOT — four more industries, each declared rather than built.
 *
 * Every pack below is a configuration file. None of them adds a line to the
 * engine: identity resolution, conflict classification, the graph, statistics
 * and the entire interface are the same code serving the hospital.
 *
 * Read one of them to see exactly what onboarding a new industry costs — the
 * vocabulary, the systems, which system carries which field, how much data to
 * generate, and which of the standard failure modes to inject.
 *
 * All data is synthetic. Every organization, person and identifier is invented.
 */
(function (SOT) {
  'use strict';

  const ROLE = (id, name, persona, maxSensitivity, scopes, blurb, landing) =>
    ({ id, name, persona, maxSensitivity, scopes, blurb, landing: landing || '#/dashboard' });

  /* ═══════════════════════════════════════════ 1 · PERSONAL SERVICES ═══════ */

  SOT.kit.define({
    id: 'salon',
    label: 'Salon & spa group',
    industry: 'Personal services',
    tenantName: 'Vestry & Bloom',
    tagline: 'Four locations, five systems, one answer about who cut whose hair.',
    domain: 'vestrybloom.example',
    seed: 5150,
    quantityHint: 'Ticket value',
    quantityFmt: 'money',
    statLabels: {
      workerEvents: 'Appointments', workerClients: 'Guests served', workerBook: 'Regular guests',
      workerGroups: 'Locations worked', workerAvg: 'Average ticket',
      clientEvents: 'Visits', clientLast: 'Last visit', clientTotal: 'Lifetime spend', clientPeople: 'Stylists seen',
      groupEvents: 'Appointments', groupStaff: 'On the floor', groupEver: 'Ever worked here',
      groupAvg: 'Average ticket', groupPerCap: 'Appointments per chair',
      siteGroups: 'Departments', siteStaff: 'Team members', siteEvents: 'Appointments',
      eventQty: 'Ticket', eventTeam: 'Team members',
    },
    types: {
      site: { label: 'Location', plural: 'Locations', kind: 'place', glyph: '▣' },
      group: { label: 'Department', plural: 'Departments', kind: 'group', glyph: '▤' },
      worker: { label: 'Team member', plural: 'Team', kind: 'person', glyph: '◍' },
      client: { label: 'Guest', plural: 'Guests', kind: 'person', glyph: '◎' },
      event: { label: 'Appointment', plural: 'Appointments', kind: 'event', glyph: '◷' },
    },
    labels: {
      'worker.credential': 'Licence', 'worker.credentialId': 'Licence number',
      'worker.credentialExpiry': 'Licence expires', 'worker.credentialStatus': 'Licence status',
      'worker.homeGroup': 'Home department', 'client.clientRef': 'Guest ID', 'client.plan': 'Membership',
      'event.quantity': 'Ticket value', 'event.outcome': 'Result', 'event.channel': 'Booked via',
      'group.capacity': 'Chairs', 'site.capacity': 'Chairs',
    },
    edgeLabels: {
      reports_to: ['Reports to', 'Direct reports'],
      assigned_to: ['Department', 'Team roster'],
      part_of: ['Location', 'Departments'],
      served_by: ['Regular stylist', 'Regular guests'],
      event_client: ['Guest', 'Visit history'],
      event_group: ['Department', 'Appointments'],
      event_team: ['Served by', 'Appointments worked'],
    },
    systems: [
      { id: 'booking', name: 'Zenora Booking', category: 'Booking & POS', idPrefix: 'ZB',
        deepLink: 'https://zenora.example/records/{id}', syncCadence: 'Every 10 minutes', volume: 9,
        blurb: 'Appointments, tickets, guest profiles, service menu.', sync: { agoMs: 7 * 60000 },
        provides: {
          site: { id: 'locationId', keys: ['code'], fields: { siteName: 'name', siteCode: 'code', city: 'city', siteType: 'kind', capacity: 'chairs' } },
          group: { id: 'deptId', keys: ['code'], fields: { groupName: 'name', groupCode: 'code', siteCode: 'locationCode', category: 'category', capacity: 'chairs' } },
          worker: { id: 'providerId', keys: ['employeeId', 'email', 'name'],
            fields: { fullName: 'displayName', workEmail: 'loginEmail', employeeId: 'staffNumber', jobTitle: 'role', credential: 'licenceType', homeGroup: 'deptCode', employmentStatus: 'status', accessStatus: 'accountStatus' } },
          client: { id: 'guestId', keys: ['mrn', 'nameDob', 'name'],
            fields: { fullName: 'guestName', clientRef: 'guestCode', dob: 'birthDate', phone: 'mobile', email: 'email', clientStatus: 'status' } },
          event: { id: 'ticketId', keys: ['code'],
            fields: { eventLabel: 'label', eventType: 'service', startAt: 'startsAt', endAt: 'endsAt', outcome: 'result', quantity: 'ticketTotal', eventStatus: 'state' } },
        } },
      { id: 'payroll', name: 'Paycove', category: 'HR & payroll', idPrefix: 'PC',
        deepLink: 'https://paycove.example/people/{id}', syncCadence: 'Nightly, 01:00', volume: 4,
        blurb: 'Employment records, start dates, employment type, terminations.', sync: { agoMs: 12 * 3600000 },
        provides: {
          worker: { id: 'employeeNumber', keys: ['employeeId', 'email', 'name'],
            fields: { fullName: 'legalName', workEmail: 'workEmail', employeeId: 'employeeNumber', jobTitle: 'position', homeGroup: 'department', employmentStatus: 'employmentStatus', employmentType: 'workerType', hireDate: 'startDate' } },
        } },
      { id: 'shifts', name: 'ShiftMate', category: 'Scheduling', idPrefix: 'SM',
        deepLink: 'https://shiftmate.example/staff/{id}', syncCadence: 'Hourly', volume: 22,
        blurb: 'Rotas, floor assignments, hours worked.',
        sync: { agoDays: 5, status: 'degraded', message: 'API key rotated on 5 Feb and never updated. No successful poll in five days.' },
        provides: {
          worker: { id: 'rotaId', keys: ['employeeId', 'name'], badge: true,
            fields: { fullName: 'name', employeeId: 'staffNo', homeGroup: 'homeDept', jobTitle: 'shiftRole', employmentStatus: 'rotaStatus' } },
          group: { id: 'rotaDeptId', keys: ['code'], fields: { groupName: 'label', groupCode: 'code', costCenter: 'costCode' } },
        } },
      { id: 'licensing', name: 'State Board Registry', category: 'Licensing', idPrefix: 'SB',
        deepLink: 'https://board.example/licence/{id}', syncCadence: 'Weekly, Monday', volume: 2,
        blurb: 'Cosmetology and massage licences, status and expiry.', sync: { agoDays: 4 },
        provides: {
          worker: { id: 'licenceRecord', keys: ['employeeId', 'name'], only: (e) => !!e.f.credential,
            fields: { fullName: 'licenseeName', employeeId: 'employerRef', credential: 'licenceClass', credentialId: 'licenceNo', credentialExpiry: 'expiresOn', credentialStatus: 'standing' } },
        } },
      { id: 'loyalty', name: 'Bloom Rewards', category: 'CRM & loyalty', idPrefix: 'BR',
        deepLink: 'https://rewards.example/member/{id}', syncCadence: 'Every 4 hours', volume: 6,
        blurb: 'Membership tiers, contact preferences, spend history.', sync: { agoMs: 5 * 3600000 },
        provides: {
          client: { id: 'memberId', keys: ['mrn', 'nameDob', 'name'],
            fields: { fullName: 'memberName', clientRef: 'guestCode', dob: 'dateOfBirth', phone: 'phone', email: 'contactEmail', address: 'postalAddress', plan: 'tier' } },
          event: { id: 'earnId', keys: ['code'], fields: { quantity: 'spend', channel: 'source' } },
        } },
    ],
    systemRoles: { master: 'booking', hr: 'payroll', schedule: 'shifts', credential: 'licensing', billing: 'loyalty', primary: 'booking', access: 'booking' },
    policy: {
      fullName: ['payroll', 'booking', 'shifts', 'licensing'],
      employeeId: ['payroll', 'booking', 'shifts'],
      jobTitle: ['payroll', 'booking', 'shifts'],
      homeGroup: ['shifts', 'booking', 'payroll'],
      employmentStatus: ['payroll', 'booking'],
      credential: ['licensing', 'booking'],
      credentialExpiry: ['licensing'],
      clientRef: ['booking', 'loyalty'],
      dob: ['booking', 'loyalty'],
      phone: ['booking', 'loyalty'],
      quantity: ['booking', 'loyalty'],
    },
    rationale: {
      homeGroup: 'The rota decides where somebody actually works this week. Payroll holds the position’s department, which changes far more slowly.',
      credentialExpiry: 'The state board is the only authority on a licence. Anything else is a copy somebody typed in.',
      quantity: 'The till is the record of what was charged. Loyalty accrues from a feed and drifts when a ticket is voided and re-rung.',
    },
    impact: {
      credentialExpiry: 'An expired licence means the service was performed illegally. Insurance and the state board both care.',
      employmentStatus: 'A leaver who still has till and booking access can take payments and refund them to themselves.',
      quantity: 'Commission, loyalty accrual and daily takings all read the ticket. Two numbers means one of them pays the wrong person.',
    },
    roles: [
      ROLE('owner_gm', 'Group manager', 'Operations Director', 'confidential',
        { site: 'all', group: 'all', worker: 'all', client: 'all', event: 'all' },
        'Every location: takings, rosters, licences and the records that disagree.'),
      ROLE('salon_mgr', 'Salon manager', 'Manager, Fitzroy Lane', 'protected',
        { site: 'all', group: 'all', worker: 'group', client: 'group', event: 'group' },
        'One department: its team, its appointments and its guests.', '#/me'),
      ROLE('stylist', 'Senior stylist', 'Senior Stylist', 'protected',
        { site: 'all', group: 'all', worker: 'all', client: 'book', event: 'book' },
        'Their own column: their guests, their appointments, their numbers.', '#/me'),
      ROLE('salon_hr', 'People & compliance', 'People Operations Lead', 'confidential',
        { site: 'all', group: 'all', worker: 'all', client: 'none', event: 'none' },
        'Licences, employment records and access. Cannot open a guest.', '#/integrity'),
    ],
    personaRules: { salon_mgr: /Department Manager/, stylist: /Senior Stylist/, owner_gm: /Operations Director/, salon_hr: /People Operations/ },
    world: {
      leadership: ['Operations Director', 'People Operations Lead', 'Regional Manager'],
      leadCredential: null,
      groupLeadTitle: 'Department Manager',
      contractorTitle: 'Chair renter',
      staleTitle: 'Stylist',
      scheduledStatus: 'Sabbatical',
      leadRole: 'Primary stylist', memberRole: 'Assisting',
      credentials: ['Cosmetology', 'Barbering', 'Massage therapy', 'Aesthetics', 'Nail technology'],
      orphanNames: ['Front Desk Terminal', 'Training Login'],
      sites: [
        { code: 'FTZ', name: 'Fitzroy Lane', city: 'Portland, OR', type: 'Flagship salon', capacity: 24 },
        { code: 'ELM', name: 'Elmwood Square', city: 'Portland, OR', type: 'Salon', capacity: 14 },
        { code: 'HRB', name: 'Harbour Row', city: 'Seattle, WA', type: 'Salon & spa', capacity: 20 },
        { code: 'CDR', name: 'Cedar Mill', city: 'Beaverton, OR', type: 'Express bar', capacity: 8 },
      ],
      groups: [
        { code: 'FTZ-CUT', name: 'Fitzroy — Cutting', site: 'FTZ', category: 'Hair', capacity: 10,
          roster: [{ title: 'Senior Stylist', count: 3 }, { title: 'Stylist', count: 4 }, { title: 'Apprentice', count: 2, credential: null }] },
        { code: 'FTZ-COL', name: 'Fitzroy — Colour', site: 'FTZ', category: 'Colour', capacity: 8,
          roster: [{ title: 'Colour Specialist', count: 4 }, { title: 'Stylist', count: 2 }] },
        { code: 'FTZ-SPA', name: 'Fitzroy — Treatment rooms', site: 'FTZ', category: 'Spa', capacity: 6,
          roster: [{ title: 'Massage Therapist', count: 3 }, { title: 'Aesthetician', count: 2 }] },
        { code: 'ELM-CUT', name: 'Elmwood — Cutting', site: 'ELM', category: 'Hair', capacity: 8,
          roster: [{ title: 'Senior Stylist', count: 2 }, { title: 'Stylist', count: 4 }] },
        { code: 'ELM-COL', name: 'Elmwood — Colour', site: 'ELM', category: 'Colour', capacity: 6,
          roster: [{ title: 'Colour Specialist', count: 3 }] },
        { code: 'HRB-CUT', name: 'Harbour — Cutting', site: 'HRB', category: 'Hair', capacity: 10,
          roster: [{ title: 'Senior Stylist', count: 2 }, { title: 'Stylist', count: 5 }] },
        { code: 'HRB-SPA', name: 'Harbour — Spa', site: 'HRB', category: 'Spa', capacity: 8,
          roster: [{ title: 'Massage Therapist', count: 4 }, { title: 'Aesthetician', count: 3 }] },
        { code: 'HRB-BRB', name: 'Harbour — Barbering', site: 'HRB', category: 'Barbering', capacity: 6,
          roster: [{ title: 'Barber', count: 4 }] },
        { code: 'CDR-EXP', name: 'Cedar Mill — Express', site: 'CDR', category: 'Hair', capacity: 8,
          roster: [{ title: 'Stylist', count: 5 }, { title: 'Apprentice', count: 1, credential: null }] },
        { code: 'FTZ-FRT', name: 'Fitzroy — Front of house', site: 'FTZ', category: 'Guest services', capacity: 4,
          roster: [{ title: 'Guest Services', count: 3, credential: null }] },
      ],
      defaultRoster: [{ title: 'Stylist', count: 4 }],
      clients: { count: 260, refPrefix: 'G-', plans: ['Bloom Gold', 'Bloom Silver', 'Pay as you go', 'Pay as you go', 'Corporate'] },
      events: {
        perClient: [1, 9], windowDays: 640,
        types: [
          { name: 'Cut & finish', hours: [1, 2], quantity: [55, 120] },
          { name: 'Colour & tone', hours: [2, 4], quantity: [110, 340] },
          { name: 'Balayage', hours: [3, 5], quantity: [180, 420] },
          { name: 'Massage — 60 min', hours: [1, 2], quantity: [90, 150] },
          { name: 'Facial', hours: [1, 2], quantity: [95, 220] },
          { name: 'Beard trim', hours: [1, 1], quantity: [25, 55] },
          { name: 'Blow-dry', hours: [1, 1], quantity: [35, 75] },
        ],
        outcomes: ['Completed', 'Completed', 'Completed', 'Completed', 'Rebooked', 'No-show', 'Redo — no charge'],
        statuses: ['Paid', 'Paid', 'Paid', 'Paid', 'Refunded', 'Comped'],
      },
    },
    anomalies: {
      ghostAccess: 2, badgeLag: 2, credentialLapsed: 4, groupTransfer: 5, credentialDrift: 3,
      idGap: 4, titleDrift: 4, scheduledChange: 2, contractors: 3, duplicateWorker: 1,
      duplicateClient: 1, clientMismatch: 5, quantityMismatch: 8, orphanAccounts: 2, costCentre: 1,
    },
  });

  /* ═══════════════════════════════════════════════ 2 · HIGHER EDUCATION ═══ */

  SOT.kit.define({
    id: 'edu',
    label: 'University',
    industry: 'Higher education',
    tenantName: 'Thornfield University',
    tagline: 'Three campuses, five systems, one answer about who is enrolled in what.',
    domain: 'thornfield.example',
    seed: 8801,
    quantityHint: 'Credit hours',
    quantityFmt: 'int',
    statLabels: {
      workerEvents: 'Sections taught', workerClients: 'Students taught', workerBook: 'Advisees',
      workerGroups: 'Departments worked', workerAvg: 'Average credit load',
      clientEvents: 'Enrolments', clientLast: 'Last enrolment', clientTotal: 'Credit hours earned', clientPeople: 'Instructors',
      groupEvents: 'Enrolments', groupStaff: 'Faculty & staff', groupEver: 'Ever taught here',
      groupAvg: 'Average credits', groupPerCap: 'Enrolments per seat',
      siteGroups: 'Departments', siteStaff: 'Faculty & staff', siteEvents: 'Enrolments',
      eventQty: 'Credit hours', eventTeam: 'Instructors',
    },
    types: {
      site: { label: 'Campus', plural: 'Campuses', kind: 'place', glyph: '▣' },
      group: { label: 'Department', plural: 'Departments', kind: 'group', glyph: '▤' },
      worker: { label: 'Faculty & staff', plural: 'Faculty & staff', kind: 'person', glyph: '◍' },
      client: { label: 'Student', plural: 'Students', kind: 'person', glyph: '◎' },
      event: { label: 'Enrolment', plural: 'Enrolments', kind: 'event', glyph: '◷' },
    },
    labels: {
      'worker.credential': 'Highest qualification', 'worker.credentialId': 'Faculty ID',
      'worker.credentialExpiry': 'Appointment ends', 'worker.credentialStatus': 'Appointment status',
      'worker.homeGroup': 'Home department', 'client.clientRef': 'Student number', 'client.plan': 'Programme',
      'event.eventType': 'Course', 'event.quantity': 'Credit hours', 'event.outcome': 'Grade',
      'event.channel': 'Programme', 'group.capacity': 'Seats', 'site.capacity': 'Seats',
    },
    edgeLabels: {
      reports_to: ['Reports to', 'Direct reports'],
      assigned_to: ['Department', 'Departmental roster'],
      part_of: ['Campus', 'Departments'],
      served_by: ['Academic adviser', 'Advisees'],
      event_client: ['Student', 'Enrolment history'],
      event_group: ['Department', 'Enrolments'],
      event_team: ['Taught by', 'Sections taught'],
    },
    systems: [
      { id: 'sis', name: 'Meridian SIS', category: 'Student records', idPrefix: 'SIS',
        deepLink: 'https://sis.thornfield.example/record/{id}', syncCadence: 'Every 30 minutes', volume: 11,
        blurb: 'Students, enrolments, course sections, departments, campuses.', sync: { agoMs: 25 * 60000 },
        provides: {
          site: { id: 'campusId', keys: ['code'], fields: { siteName: 'name', siteCode: 'code', city: 'city', siteType: 'kind', capacity: 'seats' } },
          group: { id: 'deptId', keys: ['code'], fields: { groupName: 'name', groupCode: 'code', siteCode: 'campusCode', category: 'faculty', capacity: 'seats' } },
          worker: { id: 'instructorId', keys: ['employeeId', 'email', 'name'],
            fields: { fullName: 'name', workEmail: 'email', employeeId: 'facultyNumber', jobTitle: 'rank', homeGroup: 'deptCode', employmentStatus: 'status' } },
          client: { id: 'studentId', keys: ['mrn', 'nameDob', 'name'],
            fields: { fullName: 'legalName', clientRef: 'studentNumber', dob: 'dateOfBirth', phone: 'phone', email: 'email', address: 'mailingAddress', plan: 'programme', clientStatus: 'enrolmentStatus' } },
          event: { id: 'sectionEnrolId', keys: ['code'],
            fields: { eventLabel: 'label', eventType: 'courseCode', startAt: 'termStart', endAt: 'termEnd', outcome: 'grade', quantity: 'creditHours', eventStatus: 'registrationStatus' } },
        } },
      { id: 'hcm', name: 'Thornfield HCM', category: 'HR of record', idPrefix: 'HCM',
        deepLink: 'https://hcm.thornfield.example/worker/{id}', syncCadence: 'Nightly, 02:00', volume: 4,
        blurb: 'Appointments, tenure track, employment status, departments.', sync: { agoMs: 10 * 3600000 },
        provides: {
          worker: { id: 'workerId', keys: ['employeeId', 'email', 'name'],
            fields: { fullName: 'legalName', workEmail: 'universityEmail', employeeId: 'workerId', jobTitle: 'appointmentTitle', credential: 'highestDegree', homeGroup: 'homeDept', employmentStatus: 'appointmentStatus', employmentType: 'appointmentType', hireDate: 'appointmentStart' } },
        } },
      { id: 'lms', name: 'Lantern LMS', category: 'Teaching', idPrefix: 'LMS',
        deepLink: 'https://lantern.thornfield.example/user/{id}', syncCadence: 'Hourly', volume: 30,
        blurb: 'Course shells, teaching assignments, submissions.', sync: { agoMs: 55 * 60000 },
        provides: {
          worker: { id: 'lmsUserId', keys: ['email', 'name'],
            fields: { fullName: 'displayName', workEmail: 'loginEmail', jobTitle: 'courseRole', homeGroup: 'primaryDept', accessStatus: 'accountState' } },
          event: { id: 'shellId', keys: ['code'], fields: { eventType: 'courseCode', quantity: 'credits' } },
        } },
      { id: 'idcard', name: 'Campus Card', category: 'Physical access', idPrefix: 'IDC',
        deepLink: 'https://card.thornfield.example/credential/{id}', syncCadence: 'Every 15 minutes', volume: 140,
        blurb: 'Building access, meal plans, card status, door history.', sync: { agoDays: 9, status: 'degraded', message: 'Reader gateway offline since 1 Feb. No successful poll in nine days.' },
        provides: {
          worker: { id: 'cardId', keys: ['employeeId', 'badge', 'name'], badge: true,
            fields: { fullName: 'holder', employeeId: 'personNumber', employmentStatus: 'holderStatus', accessStatus: 'cardStatus', homeGroup: 'homeBuilding' } },
          client: { id: 'studentCardId', keys: ['mrn', 'name'],
            fields: { fullName: 'holder', clientRef: 'studentNumber', clientStatus: 'cardStatus' } },
        } },
      { id: 'bursar', name: 'Bursar & Financial Aid', category: 'Finance', idPrefix: 'BUR',
        deepLink: 'https://bursar.thornfield.example/account/{id}', syncCadence: 'Every 6 hours', volume: 5,
        blurb: 'Tuition accounts, aid packages, billed credit hours.', sync: { agoMs: 4 * 3600000 },
        provides: {
          client: { id: 'accountId', keys: ['mrn', 'nameDob', 'name'],
            fields: { fullName: 'accountName', clientRef: 'studentNumber', dob: 'dateOfBirth', phone: 'billingPhone', address: 'billingAddress', plan: 'aidPackage' } },
          event: { id: 'chargeId', keys: ['code'], fields: { quantity: 'billedCredits', channel: 'fundingSource', eventStatus: 'billingStatus' } },
        } },
    ],
    systemRoles: { master: 'sis', hr: 'hcm', schedule: 'lms', credential: 'hcm', billing: 'bursar', primary: 'sis', access: 'idcard' },
    policy: {
      fullName: ['hcm', 'sis', 'lms', 'idcard'],
      employeeId: ['hcm', 'sis', 'idcard'],
      jobTitle: ['hcm', 'sis', 'lms'],
      homeGroup: ['hcm', 'sis', 'lms', 'idcard'],
      employmentStatus: ['hcm', 'sis', 'idcard'],
      clientRef: ['sis', 'bursar', 'idcard'],
      dob: ['sis', 'bursar'],
      plan: ['sis', 'bursar'],
      quantity: ['sis', 'bursar', 'lms'],
      clientStatus: ['sis', 'idcard'],
    },
    rationale: {
      quantity: 'The student system records what a student registered for. The bursar bills from a snapshot, and the two separate every time somebody drops a class after the census date.',
      clientStatus: 'Registration status is a student-records decision. The card system is downstream and should follow it, not lead it.',
      homeGroup: 'The HR appointment names the home department. Teaching systems record wherever the person happens to be teaching this term.',
    },
    impact: {
      quantity: 'Credit hours drive tuition, financial aid eligibility and full-time status. A mismatch is a bill that is wrong in one direction or the other.',
      clientStatus: 'A withdrawn student whose card still opens residence halls is both a safety issue and an audit finding.',
      employmentStatus: 'A departed member of staff with a live course shell can still see student work.',
    },
    roles: [
      ROLE('provost', 'Provost office', 'Vice Provost, Academic Affairs', 'confidential',
        { site: 'all', group: 'all', worker: 'all', client: 'all', event: 'all' },
        'The whole university, with student identifying detail redacted.'),
      ROLE('chair', 'Department chair', 'Chair, Department of History', 'protected',
        { site: 'all', group: 'all', worker: 'group', client: 'group', event: 'group' },
        'One department: its faculty, its sections and the students in them.', '#/me'),
      ROLE('adviser', 'Academic adviser', 'Senior Academic Adviser', 'protected',
        { site: 'all', group: 'all', worker: 'all', client: 'book', event: 'book' },
        'Their advisees and the enrolments attached to them.', '#/me'),
      ROLE('registrar', 'Registrar', 'Associate Registrar', 'protected',
        { site: 'all', group: 'all', worker: 'all', client: 'all', event: 'all' },
        'Student records, enrolment and every place the systems disagree.', '#/integrity'),
      ROLE('edu_hr', 'HR & access', 'Manager, Identity & Access', 'confidential',
        { site: 'all', group: 'all', worker: 'all', client: 'none', event: 'none' },
        'Appointments, cards and access. Cannot open a student record.', '#/identity'),
    ],
    personaRules: { chair: /Department Chair/, adviser: /Senior Academic Adviser/, provost: /Vice Provost/, registrar: /Registrar/, edu_hr: /Identity & Access/ },
    world: {
      leadership: ['Vice Provost', 'Manager, Identity & Access', 'Associate Registrar'],
      leadCredential: 'PhD',
      groupLeadTitle: 'Department Chair',
      contractorTitle: 'Adjunct Instructor',
      staleTitle: 'Lecturer',
      scheduledStatus: 'Sabbatical',
      leadRole: 'Instructor of record', memberRole: 'Teaching assistant',
      credentials: ['PhD', 'PhD', 'MFA', 'MSc', 'EdD'],
      orphanNames: ['Departmental Shared Account', 'Course Test Login'],
      sites: [
        { code: 'MAIN', name: 'Thornfield Main Campus', city: 'Ithaca, NY', type: 'Residential campus', capacity: 9000 },
        { code: 'RIV', name: 'Riverside Campus', city: 'Ithaca, NY', type: 'Professional studies', capacity: 2600 },
        { code: 'ONL', name: 'Thornfield Online', city: 'Remote', type: 'Distance learning', capacity: 4200 },
      ],
      groups: [
        { code: 'HIST', name: 'History', site: 'MAIN', category: 'Arts & Humanities', capacity: 320,
          roster: [{ title: 'Professor', count: 3 }, { title: 'Associate Professor', count: 3 }, { title: 'Lecturer', count: 4 }] },
        { code: 'CS', name: 'Computer Science', site: 'MAIN', category: 'Science & Engineering', capacity: 640,
          roster: [{ title: 'Professor', count: 4 }, { title: 'Associate Professor', count: 4 }, { title: 'Lecturer', count: 5 }] },
        { code: 'BIO', name: 'Biological Sciences', site: 'MAIN', category: 'Science & Engineering', capacity: 480,
          roster: [{ title: 'Professor', count: 3 }, { title: 'Associate Professor', count: 4 }, { title: 'Research Fellow', count: 3 }] },
        { code: 'ECON', name: 'Economics', site: 'MAIN', category: 'Social Sciences', capacity: 420,
          roster: [{ title: 'Professor', count: 3 }, { title: 'Lecturer', count: 5 }] },
        { code: 'ART', name: 'Fine Art', site: 'MAIN', category: 'Arts & Humanities', capacity: 180,
          roster: [{ title: 'Professor', count: 2 }, { title: 'Lecturer', count: 4 }] },
        { code: 'NURS', name: 'Nursing', site: 'RIV', category: 'Health Professions', capacity: 300,
          roster: [{ title: 'Professor', count: 2 }, { title: 'Clinical Instructor', count: 6 }] },
        { code: 'BUS', name: 'Business', site: 'RIV', category: 'Professional', capacity: 520,
          roster: [{ title: 'Professor', count: 3 }, { title: 'Lecturer', count: 6 }] },
        { code: 'EDU', name: 'Education', site: 'RIV', category: 'Professional', capacity: 260,
          roster: [{ title: 'Associate Professor', count: 3 }, { title: 'Lecturer', count: 4 }] },
        { code: 'DATA', name: 'Data Science (Online)', site: 'ONL', category: 'Science & Engineering', capacity: 700,
          roster: [{ title: 'Lecturer', count: 6 }, { title: 'Adjunct Instructor', count: 4 }] },
        { code: 'WRIT', name: 'Writing (Online)', site: 'ONL', category: 'Arts & Humanities', capacity: 400,
          roster: [{ title: 'Lecturer', count: 5 }] },
        { code: 'REG', name: 'Registrar & Student Services', site: 'MAIN', category: 'Administration', capacity: 40,
          roster: [{ title: 'Senior Academic Adviser', count: 4, credential: null }, { title: 'Records Officer', count: 3, credential: null }] },
      ],
      defaultRoster: [{ title: 'Lecturer', count: 4 }],
      clients: { count: 240, refPrefix: 'S-', plans: ['Undergraduate — full time', 'Undergraduate — part time', 'Graduate', 'Certificate', 'Exchange'] },
      events: {
        perClient: [2, 8], windowDays: 900,
        types: [
          { name: 'HIST 214 — Modern Europe', hours: [1, 3], quantity: [3, 3] },
          { name: 'CS 340 — Algorithms', hours: [1, 3], quantity: [4, 4] },
          { name: 'BIO 210 — Genetics', hours: [2, 4], quantity: [4, 4] },
          { name: 'ECON 101 — Microeconomics', hours: [1, 2], quantity: [3, 3] },
          { name: 'NURS 320 — Clinical Practice', hours: [4, 8], quantity: [6, 6] },
          { name: 'BUS 260 — Operations', hours: [1, 3], quantity: [3, 3] },
          { name: 'DATA 500 — Statistical Learning', hours: [2, 4], quantity: [4, 4] },
          { name: 'WRIT 110 — Composition', hours: [1, 2], quantity: [3, 3] },
        ],
        outcomes: ['A', 'A−', 'B+', 'B', 'B−', 'C+', 'C', 'Withdrawn', 'Incomplete'],
        statuses: ['Registered', 'Registered', 'Registered', 'Dropped', 'Audit'],
      },
    },
    anomalies: {
      ghostAccess: 3, badgeLag: 3, credentialLapsed: 0, groupTransfer: 6, credentialDrift: 3,
      idGap: 5, titleDrift: 5, scheduledChange: 3, contractors: 4, duplicateWorker: 1,
      duplicateClient: 1, clientMismatch: 6, quantityMismatch: 9, orphanAccounts: 2, costCentre: 1,
    },
  });

  /* ═══════════════════════════════════════════════ 3 · FINANCIAL SERVICES ═ */

  SOT.kit.define({
    id: 'wealth',
    label: 'Wealth management',
    industry: 'Financial services',
    tenantName: 'Halyard Wealth Partners',
    tagline: 'Three offices, five systems, one answer about who advises whom.',
    domain: 'halyardwealth.example',
    seed: 3390,
    quantityHint: 'Assets reviewed',
    quantityFmt: 'money',
    statLabels: {
      workerEvents: 'Client reviews', workerClients: 'Households served', workerBook: 'Book of business',
      workerGroups: 'Teams worked', workerAvg: 'Average review size',
      clientEvents: 'Reviews', clientLast: 'Last review', clientTotal: 'Assets under advice', clientPeople: 'Advisers involved',
      groupEvents: 'Reviews', groupStaff: 'Advisers & staff', groupEver: 'Ever on this desk',
      groupAvg: 'Average review size', groupPerCap: 'Reviews per seat',
      siteGroups: 'Desks', siteStaff: 'People', siteEvents: 'Reviews',
      eventQty: 'Assets reviewed', eventTeam: 'Advisers present',
    },
    types: {
      site: { label: 'Office', plural: 'Offices', kind: 'place', glyph: '▣' },
      group: { label: 'Desk', plural: 'Desks', kind: 'group', glyph: '▤' },
      worker: { label: 'Adviser', plural: 'Advisers & staff', kind: 'person', glyph: '◍' },
      client: { label: 'Household', plural: 'Households', kind: 'person', glyph: '◎' },
      event: { label: 'Review', plural: 'Reviews', kind: 'event', glyph: '◷' },
    },
    labels: {
      'worker.credential': 'Registration', 'worker.credentialId': 'CRD number',
      'worker.credentialExpiry': 'Registration expires', 'worker.credentialStatus': 'Registration status',
      'worker.homeGroup': 'Desk', 'client.clientRef': 'Household ID', 'client.plan': 'Service tier',
      'event.eventType': 'Review type', 'event.quantity': 'Assets reviewed', 'event.outcome': 'Outcome',
      'event.channel': 'Service tier', 'group.capacity': 'Seats', 'site.capacity': 'Seats',
    },
    edgeLabels: {
      reports_to: ['Reports to', 'Direct reports'],
      assigned_to: ['Desk', 'Desk roster'],
      part_of: ['Office', 'Desks'],
      served_by: ['Lead adviser', 'Book of business'],
      event_client: ['Household', 'Review history'],
      event_group: ['Desk', 'Reviews'],
      event_team: ['Attended by', 'Reviews attended'],
    },
    systems: [
      { id: 'crm', name: 'Beacon CRM', category: 'Client management', idPrefix: 'BC',
        deepLink: 'https://beacon.example/record/{id}', syncCadence: 'Every 15 minutes', volume: 12,
        blurb: 'Households, relationships, meetings, service tiers.', sync: { agoMs: 11 * 60000 },
        provides: {
          site: { id: 'officeId', keys: ['code'], fields: { siteName: 'name', siteCode: 'code', city: 'city', siteType: 'kind', capacity: 'seats' } },
          group: { id: 'deskId', keys: ['code'], fields: { groupName: 'name', groupCode: 'code', siteCode: 'officeCode', category: 'segment', capacity: 'seats' } },
          worker: { id: 'userId', keys: ['employeeId', 'email', 'name'],
            fields: { fullName: 'name', workEmail: 'email', employeeId: 'employeeRef', jobTitle: 'title', homeGroup: 'deskCode', employmentStatus: 'userStatus', accessStatus: 'loginState' } },
          client: { id: 'householdId', keys: ['mrn', 'nameDob', 'name'],
            fields: { fullName: 'householdName', clientRef: 'householdRef', dob: 'primaryDob', phone: 'phone', email: 'email', address: 'address', plan: 'serviceTier', clientStatus: 'relationshipStatus' } },
          event: { id: 'meetingId', keys: ['code'],
            fields: { eventLabel: 'subject', eventType: 'meetingType', startAt: 'heldAt', endAt: 'endedAt', outcome: 'outcome', quantity: 'assetsDiscussed', eventStatus: 'meetingStatus' } },
        } },
      { id: 'hris', name: 'Halyard HRIS', category: 'HR of record', idPrefix: 'HR',
        deepLink: 'https://hris.halyardwealth.example/worker/{id}', syncCadence: 'Nightly, 03:00', volume: 4,
        blurb: 'Employment, titles, desks, start and leave dates.', sync: { agoMs: 9 * 3600000 },
        provides: {
          worker: { id: 'workerId', keys: ['employeeId', 'email', 'name'],
            fields: { fullName: 'legalName', workEmail: 'workEmail', employeeId: 'workerId', jobTitle: 'jobTitle', homeGroup: 'businessUnit', employmentStatus: 'employmentStatus', employmentType: 'workerType', hireDate: 'hireDate' } },
        } },
      { id: 'custodian', name: 'Northgate Custody', category: 'Custody & billing', idPrefix: 'NC',
        deepLink: 'https://custody.example/account/{id}', syncCadence: 'Nightly, 23:00', volume: 8,
        blurb: 'Custodial accounts, balances, billed assets, statements.', sync: { agoMs: 15 * 3600000 },
        provides: {
          client: { id: 'custodyId', keys: ['mrn', 'nameDob', 'name'],
            fields: { fullName: 'registrationName', clientRef: 'householdRef', dob: 'dateOfBirth', address: 'mailingAddress', phone: 'phoneOnFile', plan: 'feeSchedule' } },
          event: { id: 'billingId', keys: ['code'], fields: { quantity: 'billedAssets', channel: 'feeSchedule', eventStatus: 'billingStatus' } },
        } },
      { id: 'compliance', name: 'Registration & Compliance', category: 'Regulatory', idPrefix: 'RC',
        deepLink: 'https://compliance.example/rep/{id}', syncCadence: 'Weekly, Sunday', volume: 3,
        blurb: 'Securities registrations, licences, supervisory status.', sync: { agoDays: 6 },
        provides: {
          worker: { id: 'repId', keys: ['employeeId', 'name'], only: (e) => !!e.f.credential,
            fields: { fullName: 'registeredName', employeeId: 'firmRef', credential: 'registrations', credentialId: 'crdNumber', credentialExpiry: 'renewalDue', credentialStatus: 'standing', employmentStatus: 'employmentFlag' } },
        } },
      { id: 'portfolio', name: 'Portfolio Engine', category: 'Portfolio management', idPrefix: 'PE',
        deepLink: 'https://portfolio.example/book/{id}', syncCadence: 'Hourly', volume: 26,
        blurb: 'Models, rebalancing, adviser books, trade history.', sync: { agoMs: 70 * 60000 },
        provides: {
          worker: { id: 'advisorCode', keys: ['employeeId', 'name'],
            fields: { fullName: 'advisorName', employeeId: 'employeeRef', homeGroup: 'bookCode', jobTitle: 'advisorRole' } },
          group: { id: 'bookId', keys: ['code'], fields: { groupName: 'bookName', groupCode: 'code', costCenter: 'ledgerCode' } },
        } },
    ],
    systemRoles: { master: 'crm', hr: 'hris', schedule: 'portfolio', credential: 'compliance', billing: 'custodian', primary: 'crm', access: 'crm' },
    policy: {
      fullName: ['hris', 'crm', 'compliance', 'portfolio'],
      employeeId: ['hris', 'crm', 'portfolio'],
      jobTitle: ['hris', 'crm', 'portfolio'],
      homeGroup: ['hris', 'crm', 'portfolio'],
      employmentStatus: ['hris', 'crm'],
      credential: ['compliance'],
      credentialExpiry: ['compliance'],
      clientRef: ['crm', 'custodian'],
      dob: ['crm', 'custodian'],
      plan: ['crm', 'custodian'],
      quantity: ['custodian', 'crm'],
    },
    rationale: {
      quantity: 'The custodian holds the assets and is the only party that can say what they were worth. The CRM records what an adviser said in a meeting.',
      credentialExpiry: 'Registration status comes from the regulator. A lapsed registration means the person cannot legally give advice.',
      homeGroup: 'HR names the desk. The portfolio system carries a book code that is reassigned far more often than an employment record changes.',
    },
    impact: {
      quantity: 'Advisory fees are charged on assets. A number that disagrees with the custodian is a billing error and a regulatory one.',
      credentialExpiry: 'Advice given on a lapsed registration is a reportable event, and every meeting held under it is in scope.',
      employmentStatus: 'A departed adviser with live CRM access can still see client holdings and contact details.',
    },
    roles: [
      ROLE('managing', 'Managing partner', 'Managing Partner', 'confidential',
        { site: 'all', group: 'all', worker: 'all', client: 'all', event: 'all' },
        'The whole firm, with household identifying detail redacted.'),
      ROLE('desk_head', 'Desk head', 'Head of Private Client Desk', 'protected',
        { site: 'all', group: 'all', worker: 'group', client: 'group', event: 'group' },
        'One desk: its advisers, its households and its reviews.', '#/me'),
      ROLE('advisor', 'Adviser', 'Senior Adviser', 'protected',
        { site: 'all', group: 'all', worker: 'all', client: 'book', event: 'book' },
        'Their own book of business and nothing beyond it.', '#/me'),
      ROLE('compliance_officer', 'Compliance', 'Chief Compliance Officer', 'protected',
        { site: 'all', group: 'all', worker: 'all', client: 'all', event: 'all' },
        'Registrations, supervision and every record the systems dispute.', '#/integrity'),
      ROLE('wealth_ops', 'Operations', 'Head of Operations', 'confidential',
        { site: 'all', group: 'all', worker: 'all', client: 'none', event: 'none' },
        'People, desks and access. Cannot open a household.', '#/identity'),
    ],
    personaRules: { desk_head: /Desk Head/, advisor: /Senior Adviser/, managing: /Managing Partner/, compliance_officer: /Chief Compliance/, wealth_ops: /Head of Operations/ },
    world: {
      leadership: ['Managing Partner', 'Head of Operations', 'Chief Compliance Officer'],
      leadCredential: 'Series 7, 66',
      groupLeadTitle: 'Desk Head',
      contractorTitle: 'Contract Paraplanner',
      staleTitle: 'Associate Adviser',
      scheduledStatus: 'Garden leave',
      leadRole: 'Lead adviser', memberRole: 'Supporting',
      credentials: ['Series 7, 66', 'Series 7, 63', 'CFP', 'CFA', 'Series 65'],
      orphanNames: ['Reception Terminal', 'Migration Service Account'],
      sites: [
        { code: 'BOS', name: 'Boston Office', city: 'Boston, MA', type: 'Headquarters', capacity: 90 },
        { code: 'CHI', name: 'Chicago Office', city: 'Chicago, IL', type: 'Regional office', capacity: 46 },
        { code: 'DEN', name: 'Denver Office', city: 'Denver, CO', type: 'Regional office', capacity: 28 },
      ],
      groups: [
        { code: 'BOS-PC', name: 'Boston — Private Client', site: 'BOS', category: 'Private client', capacity: 26,
          roster: [{ title: 'Senior Adviser', count: 4 }, { title: 'Adviser', count: 5 }, { title: 'Paraplanner', count: 3, credential: null }] },
        { code: 'BOS-UHNW', name: 'Boston — Ultra High Net Worth', site: 'BOS', category: 'UHNW', capacity: 14,
          roster: [{ title: 'Senior Adviser', count: 3 }, { title: 'Wealth Strategist', count: 2 }] },
        { code: 'BOS-INST', name: 'Boston — Institutional', site: 'BOS', category: 'Institutional', capacity: 16,
          roster: [{ title: 'Adviser', count: 4 }, { title: 'Analyst', count: 3, credential: null }] },
        { code: 'BOS-OPS', name: 'Boston — Operations', site: 'BOS', category: 'Operations', capacity: 20,
          roster: [{ title: 'Operations Associate', count: 5, credential: null }, { title: 'Client Service', count: 4, credential: null }] },
        { code: 'CHI-PC', name: 'Chicago — Private Client', site: 'CHI', category: 'Private client', capacity: 18,
          roster: [{ title: 'Senior Adviser', count: 3 }, { title: 'Adviser', count: 4 }] },
        { code: 'CHI-RET', name: 'Chicago — Retirement Plans', site: 'CHI', category: 'Retirement', capacity: 12,
          roster: [{ title: 'Adviser', count: 4 }, { title: 'Analyst', count: 2, credential: null }] },
        { code: 'DEN-PC', name: 'Denver — Private Client', site: 'DEN', category: 'Private client', capacity: 14,
          roster: [{ title: 'Senior Adviser', count: 2 }, { title: 'Adviser', count: 4 }] },
        { code: 'DEN-PLAN', name: 'Denver — Financial Planning', site: 'DEN', category: 'Planning', capacity: 10,
          roster: [{ title: 'Financial Planner', count: 4 }, { title: 'Paraplanner', count: 2, credential: null }] },
      ],
      defaultRoster: [{ title: 'Adviser', count: 4 }],
      clients: { count: 300, refPrefix: 'H-', plans: ['Core', 'Premier', 'Private Office', 'Retirement Plan', 'Institutional'] },
      events: {
        perClient: [1, 8], windowDays: 800,
        types: [
          { name: 'Annual review', hours: [1, 2], quantity: [180000, 4200000] },
          { name: 'Portfolio rebalance', hours: [1, 2], quantity: [120000, 2600000] },
          { name: 'Retirement planning', hours: [1, 3], quantity: [90000, 1800000] },
          { name: 'Estate planning', hours: [2, 4], quantity: [400000, 9000000] },
          { name: 'Onboarding', hours: [1, 3], quantity: [50000, 1200000] },
          { name: 'Tax review', hours: [1, 2], quantity: [70000, 1500000] },
        ],
        outcomes: ['No change', 'Rebalanced', 'Plan updated', 'Contribution increased', 'Escalated to specialist', 'Follow-up scheduled'],
        statuses: ['Billed', 'Billed', 'Billed', 'Pending', 'Disputed'],
      },
    },
    anomalies: {
      ghostAccess: 3, badgeLag: 2, credentialLapsed: 4, groupTransfer: 6, credentialDrift: 3,
      idGap: 4, titleDrift: 5, scheduledChange: 2, contractors: 3, duplicateWorker: 1,
      duplicateClient: 1, clientMismatch: 6, quantityMismatch: 10, orphanAccounts: 2, costCentre: 1,
    },
  });

  /* ═══════════════════════════════════════════════════════ 4 · LOGISTICS ═══ */

  SOT.kit.define({
    id: 'freight',
    label: 'Freight & logistics',
    industry: 'Transportation',
    tenantName: 'Cardinal Freightways',
    tagline: 'Four terminals, five systems, one answer about who hauled what.',
    domain: 'cardinalfreight.example',
    seed: 7712,
    quantityHint: 'Miles',
    quantityFmt: 'miles',
    statLabels: {
      workerEvents: 'Loads run', workerClients: 'Shippers served', workerBook: 'Dedicated accounts',
      workerGroups: 'Fleets worked', workerAvg: 'Average load',
      clientEvents: 'Loads', clientLast: 'Last shipment', clientTotal: 'Total miles', clientPeople: 'Drivers used',
      groupEvents: 'Loads', groupStaff: 'Drivers assigned', groupEver: 'Ever on this fleet',
      groupAvg: 'Average load', groupPerCap: 'Loads per tractor',
      siteGroups: 'Fleets', siteStaff: 'Drivers & staff', siteEvents: 'Loads',
      eventQty: 'Miles', eventTeam: 'Crew',
    },
    types: {
      site: { label: 'Terminal', plural: 'Terminals', kind: 'place', glyph: '▣' },
      group: { label: 'Fleet', plural: 'Fleets', kind: 'group', glyph: '▤' },
      worker: { label: 'Driver', plural: 'Drivers & staff', kind: 'person', glyph: '◍' },
      client: { label: 'Shipper', plural: 'Shippers', kind: 'person', glyph: '◎' },
      event: { label: 'Load', plural: 'Loads', kind: 'event', glyph: '◷' },
    },
    labels: {
      'worker.credential': 'Licence class', 'worker.credentialId': 'CDL number',
      'worker.credentialExpiry': 'Medical certificate expires', 'worker.credentialStatus': 'Qualification status',
      'worker.homeGroup': 'Fleet', 'client.clientRef': 'Account number', 'client.plan': 'Contract',
      'client.fullName': 'Shipper', 'client.dob': 'Account opened',
      'event.eventType': 'Lane', 'event.quantity': 'Miles', 'event.outcome': 'Delivery status',
      'event.channel': 'Contract', 'group.capacity': 'Tractors', 'site.capacity': 'Dock doors',
    },
    edgeLabels: {
      reports_to: ['Reports to', 'Direct reports'],
      assigned_to: ['Fleet', 'Fleet roster'],
      part_of: ['Terminal', 'Fleets'],
      served_by: ['Dedicated driver', 'Dedicated accounts'],
      event_client: ['Shipper', 'Shipment history'],
      event_group: ['Fleet', 'Loads'],
      event_team: ['Run by', 'Loads run'],
    },
    systems: [
      { id: 'tms', name: 'Cardinal TMS', category: 'Transport management', idPrefix: 'TMS',
        deepLink: 'https://tms.cardinalfreight.example/record/{id}', syncCadence: 'Every 5 minutes', volume: 14,
        blurb: 'Loads, lanes, terminals, fleets, shipper accounts.', sync: { agoMs: 4 * 60000 },
        provides: {
          site: { id: 'terminalId', keys: ['code'], fields: { siteName: 'name', siteCode: 'code', city: 'city', siteType: 'kind', capacity: 'docks' } },
          group: { id: 'fleetId', keys: ['code'], fields: { groupName: 'name', groupCode: 'code', siteCode: 'terminalCode', category: 'service', capacity: 'tractors' } },
          worker: { id: 'driverId', keys: ['employeeId', 'email', 'name'],
            fields: { fullName: 'driverName', workEmail: 'email', employeeId: 'driverCode', jobTitle: 'position', homeGroup: 'fleetCode', employmentStatus: 'driverStatus', accessStatus: 'portalAccess' } },
          client: { id: 'accountId', keys: ['mrn', 'name'],
            fields: { fullName: 'accountName', clientRef: 'accountNumber', phone: 'contactPhone', email: 'contactEmail', address: 'billTo', plan: 'contractType', clientStatus: 'accountStatus' } },
          event: { id: 'loadId', keys: ['code'],
            fields: { eventLabel: 'reference', eventType: 'lane', startAt: 'dispatchedAt', endAt: 'deliveredAt', outcome: 'deliveryStatus', quantity: 'dispatchMiles', eventStatus: 'loadStatus' } },
        } },
      { id: 'payroll', name: 'Driver Payroll', category: 'HR of record', idPrefix: 'DP',
        deepLink: 'https://payroll.cardinalfreight.example/worker/{id}', syncCadence: 'Nightly, 02:30', volume: 4,
        blurb: 'Employment, pay class, terminations, home terminal.', sync: { agoMs: 8 * 3600000 },
        provides: {
          worker: { id: 'payrollId', keys: ['employeeId', 'email', 'name'],
            fields: { fullName: 'legalName', workEmail: 'companyEmail', employeeId: 'employeeNo', jobTitle: 'payClass', homeGroup: 'homeFleet', employmentStatus: 'status', employmentType: 'engagement', hireDate: 'hiredOn' } },
        } },
      { id: 'eld', name: 'RoadSense ELD', category: 'Telematics', idPrefix: 'RS',
        deepLink: 'https://roadsense.example/device/{id}', syncCadence: 'Every 2 minutes', volume: 620,
        blurb: 'Hours of service, GPS, actual miles driven, vehicle assignment.', sync: { agoMs: 3 * 60000 },
        provides: {
          worker: { id: 'eldUserId', keys: ['employeeId', 'name'], badge: true,
            fields: { fullName: 'operatorName', employeeId: 'operatorRef', homeGroup: 'assignedFleet', accessStatus: 'deviceStatus' } },
          event: { id: 'tripId', keys: ['code'], fields: { quantity: 'odometerMiles', startAt: 'tripStart', endAt: 'tripEnd' } },
        } },
      { id: 'dot', name: 'DOT Qualification File', category: 'Regulatory', idPrefix: 'DOT',
        deepLink: 'https://dqf.example/driver/{id}', syncCadence: 'Daily, 04:00', volume: 6,
        blurb: 'Commercial licences, medical certificates, endorsements, qualification status.', sync: { agoDays: 12, status: 'degraded', message: 'Vendor API contract lapsed on 29 Jan. No successful poll in twelve days.' },
        provides: {
          worker: { id: 'dqfId', keys: ['employeeId', 'name'], only: (e) => !!e.f.credential,
            fields: { fullName: 'driverName', employeeId: 'carrierRef', credential: 'licenceClass', credentialId: 'cdlNumber', credentialExpiry: 'medCertExpiry', credentialStatus: 'qualificationStatus', employmentStatus: 'employmentFlag' } },
        } },
      { id: 'billing', name: 'Freight Billing', category: 'Revenue', idPrefix: 'FB',
        deepLink: 'https://billing.cardinalfreight.example/invoice/{id}', syncCadence: 'Every 3 hours', volume: 7,
        blurb: 'Invoices, billed miles, accessorials, shipper billing details.', sync: { agoMs: 2 * 3600000 },
        provides: {
          client: { id: 'billingAccountId', keys: ['mrn', 'name'],
            fields: { fullName: 'billToName', clientRef: 'accountNumber', phone: 'apPhone', address: 'remitTo', plan: 'rateAgreement' } },
          event: { id: 'invoiceId', keys: ['code'], fields: { quantity: 'billedMiles', channel: 'rateAgreement', eventStatus: 'invoiceStatus' } },
        } },
    ],
    systemRoles: { master: 'tms', hr: 'payroll', schedule: 'eld', credential: 'dot', billing: 'billing', primary: 'tms', access: 'eld' },
    policy: {
      fullName: ['payroll', 'tms', 'dot', 'eld'],
      employeeId: ['payroll', 'tms', 'eld'],
      jobTitle: ['payroll', 'tms'],
      homeGroup: ['tms', 'payroll', 'eld'],
      employmentStatus: ['payroll', 'tms', 'dot'],
      credential: ['dot'],
      credentialExpiry: ['dot'],
      clientRef: ['tms', 'billing'],
      plan: ['tms', 'billing'],
      quantity: ['eld', 'tms', 'billing'],
      startAt: ['tms', 'eld'],
    },
    rationale: {
      quantity: 'The electronic logging device records what the truck actually did. Dispatch holds a planned figure and billing holds a contracted one — all three are legitimate, and all three are different.',
      credentialExpiry: 'The qualification file is the regulator-facing record. A driver dispatched on an expired medical certificate is an out-of-service violation.',
      homeGroup: 'Dispatch owns which fleet a driver is running today. Payroll holds the home terminal, which changes when the job changes, not when the week does.',
    },
    impact: {
      quantity: 'Driver pay, fuel tax filing and customer invoices are all computed from miles. Three numbers means at least two of them are wrong.',
      credentialExpiry: 'Dispatching an unqualified driver is a violation per load, and every load run under it is discoverable.',
      employmentStatus: 'A separated driver still marked active can be dispatched, and still has portal access to customer manifests.',
    },
    roles: [
      ROLE('vp_ops', 'VP Operations', 'Vice President, Operations', 'confidential',
        { site: 'all', group: 'all', worker: 'all', client: 'all', event: 'all' },
        'Every terminal: fleets, loads, qualification and the records that disagree.'),
      ROLE('terminal_mgr', 'Terminal manager', 'Terminal Manager, Joliet', 'protected',
        { site: 'all', group: 'all', worker: 'group', client: 'group', event: 'group' },
        'One fleet: its drivers, its loads and the shippers on them.', '#/me'),
      ROLE('dispatcher', 'Dispatcher', 'Senior Dispatcher', 'protected',
        { site: 'all', group: 'all', worker: 'all', client: 'book', event: 'book' },
        'Their dedicated accounts and the loads attached to them.', '#/me'),
      ROLE('safety', 'Safety & compliance', 'Director of Safety', 'protected',
        { site: 'all', group: 'all', worker: 'all', client: 'all', event: 'all' },
        'Qualification files, hours of service and every disputed record.', '#/integrity'),
      ROLE('freight_hr', 'Driver services', 'Manager, Driver Services', 'confidential',
        { site: 'all', group: 'all', worker: 'all', client: 'none', event: 'none' },
        'Employment, licensing and access. Cannot open a shipper account.', '#/identity'),
    ],
    personaRules: { terminal_mgr: /Fleet Manager/, dispatcher: /Senior Dispatcher/, vp_ops: /Vice President/, safety: /Director of Safety/, freight_hr: /Driver Services/ },
    world: {
      leadership: ['Vice President, Operations', 'Manager, Driver Services', 'Director of Safety'],
      leadCredential: null,
      groupLeadTitle: 'Fleet Manager',
      contractorTitle: 'Owner-operator',
      staleTitle: 'Driver',
      scheduledStatus: 'Leave of absence',
      leadRole: 'Driver', memberRole: 'Co-driver',
      credentials: ['CDL Class A', 'CDL Class A', 'CDL Class A — Hazmat', 'CDL Class B'],
      orphanNames: ['Yard Kiosk', 'Integration Service Account'],
      sites: [
        { code: 'JOL', name: 'Joliet Terminal', city: 'Joliet, IL', type: 'Line-haul hub', capacity: 60 },
        { code: 'DAL', name: 'Dallas Terminal', city: 'Dallas, TX', type: 'Line-haul hub', capacity: 48 },
        { code: 'ATL', name: 'Atlanta Terminal', city: 'Atlanta, GA', type: 'Cross-dock', capacity: 34 },
        { code: 'RNO', name: 'Reno Terminal', city: 'Reno, NV', type: 'Cross-dock', capacity: 22 },
      ],
      groups: [
        { code: 'JOL-LH', name: 'Joliet — Line Haul', site: 'JOL', category: 'Line haul', capacity: 22,
          roster: [{ title: 'Driver', count: 9 }, { title: 'Senior Dispatcher', count: 2, credential: null }] },
        { code: 'JOL-REG', name: 'Joliet — Regional', site: 'JOL', category: 'Regional', capacity: 16,
          roster: [{ title: 'Driver', count: 8 }] },
        { code: 'JOL-MNT', name: 'Joliet — Maintenance', site: 'JOL', category: 'Maintenance', capacity: 10,
          roster: [{ title: 'Diesel Technician', count: 5, credential: null }] },
        { code: 'DAL-LH', name: 'Dallas — Line Haul', site: 'DAL', category: 'Line haul', capacity: 20,
          roster: [{ title: 'Driver', count: 9 }, { title: 'Senior Dispatcher', count: 1, credential: null }] },
        { code: 'DAL-HAZ', name: 'Dallas — Hazmat', site: 'DAL', category: 'Specialised', capacity: 10,
          roster: [{ title: 'Driver', count: 6 }] },
        { code: 'DAL-DED', name: 'Dallas — Dedicated', site: 'DAL', category: 'Dedicated', capacity: 12,
          roster: [{ title: 'Driver', count: 7 }] },
        { code: 'ATL-REG', name: 'Atlanta — Regional', site: 'ATL', category: 'Regional', capacity: 14,
          roster: [{ title: 'Driver', count: 8 }] },
        { code: 'ATL-LTL', name: 'Atlanta — LTL City', site: 'ATL', category: 'City delivery', capacity: 12,
          roster: [{ title: 'Driver', count: 6 }, { title: 'Dock Supervisor', count: 2, credential: null }] },
        { code: 'RNO-LH', name: 'Reno — Line Haul', site: 'RNO', category: 'Line haul', capacity: 12,
          roster: [{ title: 'Driver', count: 7 }] },
        { code: 'JOL-DSP', name: 'Joliet — Dispatch', site: 'JOL', category: 'Dispatch', capacity: 8,
          roster: [{ title: 'Senior Dispatcher', count: 3, credential: null }, { title: 'Load Planner', count: 3, credential: null }] },
      ],
      defaultRoster: [{ title: 'Driver', count: 6 }],
      clients: { count: 180, refPrefix: 'A-', plans: ['Contract — dedicated', 'Contract — volume', 'Spot market', 'Brokerage', 'Contract — dedicated'] },
      events: {
        perClient: [2, 14], windowDays: 520,
        types: [
          { name: 'Joliet → Dallas', hours: [14, 22], quantity: [920, 1010] },
          { name: 'Dallas → Atlanta', hours: [12, 18], quantity: [770, 830] },
          { name: 'Atlanta → Joliet', hours: [12, 20], quantity: [690, 750] },
          { name: 'Reno → Dallas', hours: [24, 34], quantity: [1580, 1720] },
          { name: 'Joliet metro LTL', hours: [4, 9], quantity: [40, 180] },
          { name: 'Dallas → Reno', hours: [24, 34], quantity: [1560, 1700] },
          { name: 'Atlanta metro LTL', hours: [4, 9], quantity: [35, 165] },
        ],
        outcomes: ['Delivered on time', 'Delivered on time', 'Delivered on time', 'Delivered late', 'Refused at dock', 'Rescheduled'],
        statuses: ['Invoiced', 'Invoiced', 'Invoiced', 'Held — paperwork', 'Disputed'],
      },
    },
    anomalies: {
      ghostAccess: 3, badgeLag: 3, credentialLapsed: 5, groupTransfer: 7, credentialDrift: 3,
      idGap: 5, titleDrift: 4, scheduledChange: 2, contractors: 4, duplicateWorker: 1,
      duplicateClient: 1, clientMismatch: 5, quantityMismatch: 12, orphanAccounts: 2, costCentre: 1,
    },
  });
})(window.SOT || (window.SOT = {}));
